[server]
port = 3000
host = "0.0.0.0"

[database]
driver = "sqlite"
file = "data/sqlite.db"

[[models]]
id = "yolo26n"
name = "YOLO26-n"
api_url = "http://127.0.0.1:5000/model/yolo26n"
api_key = ""

[[models]]
id = "yolo26-seg"
name = "YOLO26-Seg"
api_url = "http://127.0.0.1:5000/model/yolo26-seg"
api_key = ""